services:
  - type: web
    name: patita-solidaria-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: dbPatitaSolidaria
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: dbPatitaSolidaria
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: dbPatitaSolidaria
          property: password
