services:
  - type: web
    name: patita-solidaria-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/BackEnd-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: JDBC_DATABASE_URL
        value: your-database-url
      - key: JDBC_DATABASE_USERNAME
        value: your-username
      - key: JDBC_DATABASE_PASSWORD
        value: your-password
      - key: JWT_SECRET
        value: your-secret-key
