services:
  - type: web
    name: patita-solidaria-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/BackEnd-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JDBC_DATABASE_URL
        value: "jdbc:postgresql://dpg-d15lftu3jp1c73bee130-a.oregon-postgres.render.com:5432/patita_solidaria"
      - key: JDBC_DATABASE_USERNAME
        value: "admin_patita"
      - key: JDBC_DATABASE_PASSWORD
        value: "nWVZL5sHkKhSyBUsOAv1quES4K8ACdSk"
